# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a93cdaa401cc49b1ee1cb47a12208506eb2ebfca17348c4502a6db73b8df2688cde182cdfee47000e4dee30859e00862bebb0e91d89fc5189471c8383e421c8

test:
  secret_key_base: 7029e3168299bdfab0b7daafe73393108a4eab2784f09f1a22590ada77372655eacef09df9cdba8cb1f2028ffc83856f5d7bebb3dca44f5dc795285a520f39d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 0a93cdaa401cc49b1ee1cb47a12208506eb2ebfca17348c4502a6db73b8df2688cde182cdfee47000e4dee30859e00862bebb0e91d89fc5189471c8383e421c8
#<%= ENV["SECRET_KEY_BASE"] %>
